#!/usr/bin/env python

import os
from diffusers import StableDiffusionPipeline


model_id = "stabilityai/stable-diffusion-2-1"
MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
)
