#!/usr/bin/env python

import os
import shutil
import torch
from diffusers import (
    KandinskyInpaintPipeline,
    KandinskyImg2ImgPipeline,
    KandinskyPriorPipeline,
    KandinskyPipeline,
)


MODEL_CACHE = "model_cache"


if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


inpaint_pipe = KandinskyInpaintPipeline.from_pretrained(
    "kandinsky-community/kandinsky-2-1-inpaint",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
)

pipe_prior = KandinskyPriorPipeline.from_pretrained(
    "kandinsky-community/kandinsky-2-1-prior",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
)

t2i_pipe = KandinskyPipeline.from_pretrained(
    "kandinsky-community/kandinsky-2-1",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
)

pipe = KandinskyImg2ImgPipeline.from_pretrained(
    "kandinsky-community/kandinsky-2-1",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
)
