#!/usr/bin/env python

import os
import shutil
import torch
from diffusers import StableDiffusionDiffEditPipeline

MODEL_CACHE = "diffusers-cache"


if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipeline = StableDiffusionDiffEditPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1",
    torch_dtype=torch.float16,
    cache_dir=MODEL_CACHE,
    safety_checker=None,
)
